language: generic

services:
  - docker

before_script:
  # Login to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build images for each subfolder
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed adelekand/udagram-api-feed

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user adelekand/udagram-api-user

  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy adelekand/reverseproxy

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend adelekand/udagram-frontend

after_success:
  # Push images to DockerHub
  - docker push adelekand/udagram-api-feed
  - docker push adelekand/udagram-api-user
  - docker push adelekand/reverseproxy
  - docker push adelekand/reverseproxy
