version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use an appropriate base image
    working_directory: ~/repo

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and tag Docker images
          command: |
            # Login to DockerHub
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

            # Build and tag images
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed adelekand/udagram-api-feed

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user adelekand/udagram-api-user

            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy adelekand/reverseproxy

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend adelekand/udagram-frontend

      - run:
          name: Push Docker images to DockerHub
          command: |
            docker push adelekand/udagram-api-feed
            docker push adelekand/udagram-api-user
            docker push adelekand/reverseproxy
            docker push adelekand/udagram-frontend

workflows:
  version: 2
  build:
    jobs:
      - build-and-push
